// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class StageFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlyOwGfWvZbzrjbVWpf2jlCwzvlCOzjaM',
    appId: '1:491487191546:android:56611140049f85d5b8c443',
    messagingSenderId: '491487191546',
    projectId: 'todo-a0d9d',
    storageBucket: 'todo-a0d9d.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCCT1O-7gsRQbPZ_LgOdD1c5CHhFxQBzj4",
      authDomain: "todo-a0d9d.firebaseapp.com",
      projectId: "todo-a0d9d",
      storageBucket: "todo-a0d9d.appspot.com",
      messagingSenderId: "491487191546",
      appId: "1:491487191546:web:0e2b0c87a0002be3b8c443",
      measurementId: "G-7PYJ0JM0JG");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosBundleId: 'com.example.stage4Thisday',
  );
}
